### ISSUE TITLE
Latest release 2.4.3 not available

### ISSUE THREAD

**Issue by screendriver** [solokeys/solo-webupdate#16]
The [latest release](https://github.com/solokeys/solo/releases/tag/2.4.3) `2.4.3` is not available on the website. It still shows that the latest version is `2.4.2`

**Comment by nickray** [comment]
Soon..

**Comment by nickray** [comment]
@screendriver Done. FYI, the *official* release is always what https://raw.githubusercontent.com/solokeys/solo/master/STABLE_VERSION points to.

This kind of thing should be automated soon-ish via https://github.com/solokeys/solo/issues/277

**Comment by screendriver** [comment]
Awesome. Thanks :+1:
