### ISSUE TITLE
Webupdate: SITE FIRMWARE OUT OF DATE!

### ISSUE THREAD

**Issue by jolo1581** [solokeys/solo-webupdate#17]
Hello,

today I can't update my solokey secure. The website says: SITE FIRMWARE OUT OF DATE!

**Comment by huaracheguarache** [comment]
I get the same message on the website, and I think this is due to the latest release not including a firmware-secure-2.5.1.sha2 file. When I tried to run solo-webupdate locally I got the following error message:

```
+ wget -P data/ https://github.com/solokeys/solo/releases/download/2.5.1/firmware-secure-2.5.1.sha2
--2019-08-29 22:56:42--  https://github.com/solokeys/solo/releases/download/2.5.1/firmware-secure-2.5.1.sha2
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-08-29 22:56:43 ERROR 404: Not Found.

make: *** [Makefile:13: fetch-firmware] Error 8
```

**Comment by nickray** [comment]
Yep, thanks for pointing this out. It's redeployed. If one of you has an idea how to setup a GitHub Action to kick off the Netlify redeploy after `STABLE_VERSION` gets bumped, please share :)
