### ISSUE TITLE
Inspect key brings up multiple pin prompts

### ISSUE THREAD

**Issue by My1** [solokeys/solo-webupdate#19]
there are 3 pin prompts when going to "Inspect key", might it not be useful to use "discouraged" for userverification so that it is a bit easier to use?

**Comment by nickray** [comment]
Can you setup a PR?

**Comment by My1** [comment]
just wrote the fix and noted something kinda interesting and/or weird/concerining.

accioding to webauthn, user presence is always supposed to be the inverse of verification, (because verification already does presence along the way, we dont need to ask extra), but the fun part is that a part of the requests literally just goes through with no presence confirmation.

just did the fork and editing the files in git, the PR should be in in a few minutes.

Edit: #20 is in.
