### ISSUE TITLE
Vue is in development mode

### ISSUE THREAD

**Issue by keysmashes** [solokeys/solo-webupdate#21]
On https://update.solokeys.com/:

> You are running Vue in development mode.
> Make sure to turn on production mode when deploying for production.
> See more tips at https://vuejs.org/guide/deployment.html

**Comment by nickray** [comment]
Is this an issue or an observation?

**Comment by keysmashes** [comment]
Just an observation.

**Comment by nickray** [comment]
Feel free to send a PR if it bugs you. The idea was that some may want to run a local version, perhaps modified, and this would help debug/inspect.
