### ISSUE TITLE
Something went wrong, device is not in bootloader mode

### ISSUE THREAD

**Issue by sl4m** [solokeys/solo-webupdate#3]
Tried updating the Solo Hacker as it would not work correctly as a security key, but having problems updating the firmware.

<img width="449" alt="Screenshot 2019-03-17 at 09 57 38" src="https://user-images.githubusercontent.com/47347/54488590-5681f900-489b-11e9-94b2-d8a88a8f0846.png">

<img width="700" alt="Screenshot 2019-03-17 at 09 55 48" src="https://user-images.githubusercontent.com/47347/54488593-5b46ad00-489b-11e9-8f37-b70e35bebd2c.png">

**Comment by conorpp** [comment]
Can you do the following?
1. Unplug key
2. Hold button down.
3. Plug in while holding button down for 2 secounds, until LED starts flashing.

Once in fast flashing LED state, it is ready for update.

**Comment by sl4m** [comment]
@conorpp Thanks for the reply. When should I be doing this? I've tried following your steps in various stages, but can't seem to get past the Inspect Key stage.

Also, which option should I be using to verify my identity?

<img width="448" alt="Screenshot 2019-03-17 at 20 07 04" src="https://user-images.githubusercontent.com/47347/54497250-42b4b200-48f0-11e9-922f-2587ad261c77.png">

**Comment by conorpp** [comment]
Should be used normally for inspect key stage, choose USB security key.  Then switch key into update/bootloader mode.

**Comment by sl4m** [comment]
I've tried everything and nothing seems to work. Is it possible I have a dud? Before this, I tried using this. It registered fine, but I was not able to use it after to prove my identity

**Comment by conorpp** [comment]
Can you put the key in bootloader mode?  The LED should be a fast-flashing yellow.
