### ISSUE TITLE
Ubuntu doesn't work

### ISSUE THREAD

**Issue by ryandaniels** [solokeys/solo-webupdate#4]
Update website (https://update.solokeys.com/) doesn't detect key when using "Inspect Key" button on Ubuntu.
Tested on latest Firefox.
Solo Secure key.

On Ubuntu (18.04) using Firefox nothing is detected, and yellow LED does not flash.
On Windows using Firefox it worked.

**Comment by ryandaniels** [comment]
Fixed after finding info in FAQ to add udev rules: https://docs.solokeys.io/solo/udev/

Suggestion: If Ubuntu is detected on update page (or maybe non-Windows), point user to udev rules info.

**Comment by conorpp** [comment]
Good idea to detect browser.  Many people do not know about the udev issue.  Anyone know a good way to do that with JavaScript?

**Comment by nickray** [comment]
We detect OS in webupdate :)

**Comment by nickray** [comment]
We now warn that udev rules are needed if the OS is Linux: https://github.com/solokeys/solo-webupdate/commit/effefc4b5251ff8d7441f326457e23d4c0ad2dbc
