### ISSUE TITLE
Solokey stuck in bootloader after attempting to update

### ISSUE THREAD

**Issue by jasperweiss** [solokeys/solo-webupdate#7]
After attempting to update my Solo (secure) key, it got stuck in the bootloader mode (LED flashes red rapidly as soon as I plug it in)
I've tried reflashing it but it doesn't do much. The console lists this error among other things: 

`Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at update (main.js:289)
    at async update_secure (main.js:252)`

I wanted to try reflashing it using the Python tool with no succes:

`C:\Users\user>solo key update --secure`
``
`No Solo key found!`
``
`If you are on Linux, are your udev rules up to date?`
`Try adding a rule line such as the following:`
`ATTRS{idVendor}=="0483", ATTRS{idProduct}=="a2ca", TAG+="uaccess"`
`For more, see https://docs.solokeys.io/solo/udev/`

I'm guessing it's bricked. Is there a way to reflash the firmware at this point? 

edit: So I've tried running `solo program bootloader firmware-secure-2.2.0.json` but that also results in a `solo.exceptions.NoSoloFoundError: no Solo found` 

Neither the bootloader interface, the dfu interface or the aux commands work.

**Comment by jasperweiss** [comment]
I was able to restore (reflash) it today under the advanced tab on the update site. (albeit it with a flickering Windows Hello prompt every 0.2 seconds)

**Comment by jasperweiss** [comment]
Although the solo is working again, the solo-python tool still reports `solo.exceptions.NoSoloFoundError: no Solo found` and
`>solo ls`
`:: Solos`

**Comment by conorpp** [comment]
Does it show up in device manager as a security key?  The update likely allowed windows to properly recognize it as a FIDO 2 key and elevate the required permissions to interact with it (not sure why).  I've found that running `solo ls` from an administrator prompt to work.

Not sure yet how to access properly without admin.

**Comment by jasperweiss** [comment]
Yes, for some reason `solo ls` works fine if you're running cmd as admin. But `solo key update` doesn't work (see errors [here](https://gist.github.com/Bodup/e7102ca829a498a69d0e8bc92aac50a5)) nor does `solo program bootloader bootloader-verifying-2.2.2.hex` (see errors [here](https://gist.github.com/Bodup/49b32b8b1a7012b423dd4a0440c2f1d6)). `solo key verify` doesn't work either since it requires a pin (which it doesn't allow you to input). I think the latter issue has been filed already on the solo-python issue tracker.

As for the solo-webupdate, strangely enough this was the only workable solution to flashing my solo by going to advanced mode and reflashing it there. But it gets interrupted every 0.2 seconds or so by the Windows WebAuthn API prompt, see [here](https://imgur.com/a/aGBrXJa). (note that this behavior is only seen on Windows 1903 which isn't available outside of the Windows insiders builds just yet.)

**Comment by nickray** [comment]
The flashing thing is just evidence of our abuse of WebAuthn (and it behaves a little bit differently depending on the browser). What we do is send a specially crafted getAssertion request. This causes a popup, which normally would wait for the user to press, but the key reacts "silently" in the sense of responding without the button press, which makes the popup go away. And then this repeats until the update is done.

**Comment by nickray** [comment]
I think we can close this issue @Bodup?

**Comment by jasperweiss** [comment]
Yup
